### ISSUE TITLE
Config files not generating on launch for 2.0.1

### ISSUE THREAD

**Issue by ytitnE** [taffyko/LCBetterSprayPaint#10]
A couple of my profiles on thunderstore aren't generating the config files and isn't showing up on lethalconfig and not working in game. The first profile I updated actually generated and still works. I've tested it on a fresh profile and it does the same thing. I've tried to reinstalling and such but no luck. When I revert back to 1.1.0 it works, and tried updated it and nothing

**Comment by stuwaper** [comment]
The following content was translated using software
After the update, my mod became invalid. I deleted the configuration file but the issue was the same as before. I uninstalled and rolled back to version 1.10, then upgraded to version 2.0.1 one by one, and the mod worked normally

**Comment by ytitnE** [comment]
I tried that, no luck

**Comment by ytitnE** [comment]
It seems the mod is not downloading the dependencies it needs. Cause it shows in the cmd when launching that it needs LC InputUtils. It works now with it.

**Comment by stuwaper** [comment]
> It seems the mod is not downloading the dependencies it needs. Cause it shows in the cmd when launching that it needs LC InputUtils. It works now with it.

The following content was translated using software
As you said, I also noticed, but this LC InputUtils will reduce the success rate of joining the room (sadly...)

**Comment by taffyko** [comment]
shoot, my bad! — i've added the dependency on InputUtils to the mod manifest in v2.0.2!

**Comment by stuwaper** [comment]
> shoot, my bad! — i've added the dependency on InputUtils to the mod manifest in v2.0.2!

尝试了，更新之后仍然无法加入其他人的房间，我能盼望作者在未来的更新后取消对InputUtils的依赖吗
