### ISSUE TITLE
Option to make spray paint not infinite

### ISSUE THREAD

**Issue by SeymourSchlong** [taffyko/LCBetterSprayPaint#2]
There's some aspects of the game that I like having the restrictions for, and the spray paint is kind of one of them. I'd really like to have functional spray paint but on the other hand I like to keep some limited items with their intended purpose.

**Comment by Coltrainn** [comment]
I created a PR for this already, #1. Just needs to be merged.

**Comment by taffyko** [comment]
@Coltrainn hey there! when i have a chance (likely later today or tomorrow), i'll get that PR of yours merged in and publish a release.
thanks for contributing!

**Comment by taffyko** [comment]
closed this morning with the release of 1.1.0!
