### ISSUE TITLE
Add 'Shaking the can is more effective' config toggle

### ISSUE THREAD

**Issue by SirHazza** [taffyko/LCBetterSprayPaint#3]
Amazing mod, but I would much prefer to shake the spray can as it was like in the base game. This mod, whilst fast, makes it feel 'buggy' with such a short animation playing.

Thank you.

**Comment by renatamer** [comment]
This please!

**Comment by taffyko** [comment]
working on this now! the next release will have this setting :>

**Comment by taffyko** [comment]
alrighty, v2.0.0 is finally out, thank you for your patience!
take a look at the three new shaking-related settings that are now fully configurable: `ShorterShakeAnimation`, `ShakeEfficiency`, and `ShakingNotNeeded`!

**Comment by SirHazza** [comment]
@taffyko Thank you so much for this update! Just tried it out and everything was working perfectly during my brief test. I really appreciate your hard work on this. It's likely I'm going to spend more time painting than actually collecting scrap with the new colour and size controls 😄
