### ISSUE TITLE
Clear spray paint when leaving a moon

### ISSUE THREAD

**Issue by SeymourSchlong** [taffyko/LCBetterSprayPaint#4]
I don't know whether this is fully within the scope of what this mod intends to do, but when using spray paint on the inside of a mansion or facility and going back to that moon you can still see leftover spray paint from when you were there last time.

Is it possible to have the mod clear all spray paint applied to the map either on arrival or departure? Thank you for your awesome mod <3

**Comment by SeymourSchlong** [comment]
This issue was addressed in update v47 of the base game and is no longer going to be an issue for later versions, but I'll leave this up in case the feature may be backported to prior versions (the mod is currently compatible with v45 and v47)

**Comment by taffyko** [comment]
thanks for reporting this!
i had intended to implement this (before v47 came out) but got swamped by work — going forward i likely won't be officially supporting earlier versions of the game in newer versions of the mod, but if this issue resurfaces or needs further attention i'll be sure to implement my own fix!

**Comment by SeymourSchlong** [comment]
I was playing with some friends earlier and unfortunately it seems like the spray paint still persists after leaving the moon :(

A fix would be much appreciated, whenever you have the time 😊

**Comment by taffyko** [comment]
got it, i'll see if i can manage to reproduce this!

**Comment by Lunxara** [comment]
Yeah I reported this issue before in Discord lol I managed to have the issue happen less if I didn't touch the config file at all fort some odd reason but it did eventually happen again for me when playing with my group

**Comment by taffyko** [comment]
i did manage to reproduce it! — it's not consistent, but it definitely remains an issue in the base game and i'm working on a more reliable fix in the next upcoming release!
