### ISSUE TITLE
Mod only partially works?

### ISSUE THREAD

**Issue by PunishedSnakePr** [taffyko/LCBetterSprayPaint#5]
Maybe this mod does not work in combination with other mods I have installed because this is how it behaves:
1) Console logs the mod has been loaded properly
2) Config is empty by default
3) Neither infinite spraying nor drawing a constant line works in game
4) Spray sound is also as loud as in base game
5) BUT I can erase sprayed dots

This is my mod string 018cd914-3bf5-ef3a-9798-221107aacb01

**Comment by taffyko** [comment]
hi there! i'm having trouble reproducing this issue, and the game has changed a bit with the release of v49
if this issue is still showing up for you, could you share an updated profile code with the latest mods you're using? thanks!

**Comment by PunishedSnakePr** [comment]
Hi. I can confirm it works now. Thank u! :)
