### ISSUE TITLE
Correct config?

### ISSUE THREAD

**Issue by plechovka** [taffyko/LCBetterSprayPaint#6]
I don't know if I'm having it correctly. But this should be correctly set up?

The first setting should be default or e? or someone has better experience?
Otherwise all works good
![image_2024-01-13_231813212](https://github.com/taffyko/LCBetterSprayPaint/assets/20068809/eeadfc47-7767-46d7-9d68-773f2f8d9b8e)

**Comment by taffyko** [comment]
yes!
in the description, i was just referring to the fact that `E` is the key that "Tertiary Action" is bound to by default in the game's settings — i'll probably change the wording to make this less confusing!

**Comment by plechovka** [comment]
Absolutely!
However, tried using the E button and it did not removed the spray. Dunno what I did wrong.

I'll share my profile here: **018d0493-bb17-6338-9a41-9e65cc032282**
its total of 45 mods together.

**Comment by taffyko** [comment]
i downloaded and tried out your profile, and the erase feature seems to be working!
have you made sure that you're holding both `E` _and_ the left mouse button at the same time?

**Comment by plechovka** [comment]
Holding E + left mouse button worked. Did not know have to hold both. 
But yeah, that's a good feedback as well to know. Writing it on the page for others to avoid future issues from people would be good idea.

Thank you so much for amazing mod and keep up the great work!
