### ISSUE TITLE
[Suggestion] Config for spray paint fuel

### ISSUE THREAD

**Issue by Sh0otgun** [taffyko/LCBetterSprayPaint#8]
How about a slider option in the config that can change the amount of fuel in the can?
Left side is the vanilla fuel amount, and sliding it all the way to the right will make it infinite.

**Comment by taffyko** [comment]
alright, v2.0.0 has been released, and this is now configurable!
to use it, first set `InfiniteTank` to `false`, and then set `TankCapacity` to whatever you like! (with `25.0` being the vanilla amount as documented in the config description)
